name = "LinearEquations"
uuid = "61d91b44-0d68-47b5-9a58-bd457a118ee3"
authors = ["Ruihuan Fang"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
